# Generated by Django 4.2.11 on 2024-04-14 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='devicereadings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Данные с устройства', 'verbose_name_plural': 'Данные с устройства'},
        ),
        migrations.AlterModelOptions(
            name='testinglocation',
            options={'ordering': ['name'], 'verbose_name': 'Место испытаний', 'verbose_name_plural': 'Места испытаний'},
        ),
        migrations.AddField(
            model_name='devicereadings',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата измерений'),
            preserve_default=False,
        ),
    ]
