# Generated by Django 5.0.4 on 2024-04-19 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='devicereadings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Данные с устройства', 'verbose_name_plural': 'Данные с устройства'},
        ),
        migrations.AlterModelOptions(
            name='invoce',
            options={'ordering': ['-billed_at'], 'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-visited_at'], 'verbose_name': 'Измерения', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterModelOptions(
            name='testinglocation',
            options={'ordering': ['name'], 'verbose_name': 'Место испытаний', 'verbose_name_plural': 'Места испытаний'},
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='device_readings',
        ),
        migrations.AddField(
            model_name='devicereadings',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата измерений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicereadings',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meas.measurement'),
        ),
        migrations.AlterField(
            model_name='invoce',
            name='billed_at',
            field=models.DateField(verbose_name='Дата счета'),
        ),
        migrations.RemoveField(
            model_name='invoce',
            name='measurement',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='visited_at',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='invoce',
            name='measurement',
            field=models.ManyToManyField(to='meas.measurement'),
        ),
    ]
