# Generated by Django 4.2.11 on 2024-04-19 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0002_alter_area_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoce',
            options={'ordering': ['-billed_at'], 'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-visited_at'], 'verbose_name': 'Измерения', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.RemoveField(
            model_name='invoce',
            name='measurement',
        ),
        migrations.AddField(
            model_name='measurement',
            name='invoce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoce', to='meas.invoce'),
        ),
    ]
