# Generated by Django 4.2.11 on 2024-04-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0003_alter_invoce_options_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadings',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Дата измерений'),
        ),
    ]
