# Generated by Django 5.0.4 on 2024-04-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0004_alter_measurement_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereadings',
            name='compaction_ratio',
            field=models.CharField(default='>0.95', max_length=20, verbose_name='Коэффециент уплотнения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicereadings',
            name='tag_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер метки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='create_docs',
            field=models.BooleanField(verbose_name='Созданы документы'),
        ),
    ]
