# Generated by Django 4.2.11 on 2024-04-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0006_alter_devicereadings_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadings',
            name='created_at',
            field=models.DateField(verbose_name='Дата измерений'),
        ),
    ]
