# Generated by Django 5.0.4 on 2024-05-05 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0006_alter_invoce_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='meas.customer'),
        ),
        migrations.AddField(
            model_name='area',
            name='mark',
            field=models.CharField(default='', max_length=10, verbose_name='Маркировка'),
            preserve_default=False,
        ),
    ]
