# Generated by Django 4.2.11 on 2024-04-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0007_alter_devicereadings_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoce',
            name='billed_at',
            field=models.DateField(verbose_name='Дата счета'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='visited_at',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
    ]
